android/app/build.gradle
android/app/src/main/java/com/surveyor/MainApplication.java
android/settings.gradle
docs/localization.md
i18n.js
index.android.js
index.ios.js
ios/Surveyor.xcodeproj/project.pbxproj
locale/en.js
locale/index.js

This gets initial localization set up and ready to use.
It's using the package [react-native-localization](https://npmjs.com/react-native-localization).
I started a localization docs file that will be expanded as we implement localization for all the UI components and surveys.

Localization set up

---

app/screens/Observations/map.js

closes #77 
Anything else that needs to go into this change I'm not thinking of?

use openmaptiles + osm bright

---

app/components/wrapper.js

quick fix so the hamburger menu works

make side menu openable from all pages

---

app/actions/index.js
app/components/StatusBar.js
app/reducers/surveys.js
app/screens/Account/LocalSurveyList.js
app/screens/Account/RemoteSurveyList.js
app/screens/Account/surveyChoose.js
app/screens/Account/surveys.js
app/selectors/index.js
package.json
yarn.lock

In process, but no reason that it can't be landed.

Survey management

---

app/actions/index.js
app/components/category-list.js
app/components/field-inputs.js
app/components/fields.js
app/screens/CreateObservation/add-observation.js
app/screens/CreateObservation/categories.js
app/selectors/index.js
package.json
yarn.lock

Moves closer to being able to input observation data via fields.

Categorization, etc

---

app/components/category-list.js
app/screens/App/index.js
app/screens/Observations/create.js

Dropped the animating because it wasn't straightforward how to add it in. We can re-add it in the future.

Turn category list into a SectionList

---

app/components/side-menu.js

this closes #131 and closes #151

add clickable overlay to sidemenu and remove close button

---

app/components/category-list.js
app/components/field-inputs.js
app/screens/App/index.js
app/screens/Observations/categories.js
app/screens/Observations/create.js
app/screens/Observations/fieldset-form.js
app/selectors/index.js

Progress on fields that hold state, even if it's not yet wired up to individual observations.

Fields that fill

---

app/actions/index.js
app/reducers/surveys.js
app/screens/Account/LocalSurveyList.js

delete survey with confirmation

---

android/app/src/main/res/values/strings.xml
android/settings.gradle
app.json

This makes it so the app shows up as `Observe` in the android ui

rename surveyor to observe in android app

---

app/components/location-modal.js
app/components/map.js
app/screens/Observation/view.js
app/styles/index.js

This gets the location modal working.

Location modal

---

app/actions/index.js
app/reducers/observation.js
app/screens/App/index.js
app/screens/Observation/map.js
app/selectors/index.js

* correctly propagate `surveyId`

Miscellany

---

app/components/map-overlay.js
app/lib/osm-p2p.js
app/screens/Account/LocalSurveyList.js
app/screens/Account/observations.js
app/screens/Observation/map.js
app/screens/Observation/view.js
app/selectors/index.js

Shows observation count in:
- local survey list
- nearby points on main map view

Observation count

---

app/lib/convert-geojson-osmp2p.js
app/lib/osm-import.js

this fixes the timestamp part of #247

use existing timestamp if available

---

app/screens/Observation/view.js

this adds an alert if the lat/lon is not presnet on the observation when a user presses the save button

alert user if lat/lon havent been added to observation

---

app/components/fields.js

As far as I can tell @felskia #250 only refers to combo fields. This should fix it.

Closes #250

---

app/lib/calculate-completeness.js
app/screens/Account/LocalSurveyList.js
app/screens/Account/observations.js
app/screens/Account/survey.js
app/screens/App/index.js

[wip] Closes #190

---

app/actions/index.js
app/reducers/observation.js
app/reducers/status.js
app/screens/Observation/view.js

@sethvincent on save observation, I set the active observation to be the saved data. Do you think this might cause a regression somewhere else?

Close #251

---

app/components/annotation-observation.js
app/screens/Account/observations.js
app/screens/Account/survey.js
app/screens/Observation/choose-point.js
app/screens/Observation/fieldset-form.js
app/screens/Observation/map.js
app/screens/Observation/view.js

Could you take a quick look for style @felskia ?

Closes #240

---

app/screens/OsmFeature/view.js

Closes #271

---

app/components/fields.js
app/screens/Observation/view.js
app/styles/index.js

@felskia this needs a bit of styling I think

Allow user to change observation type

---

app/screens/Observation/map.js

wait until we have users current position to update bounds

---

app/components/map-overlay.js
app/screens/Observation/map.js

@sethvincent I think this addresses #254, but would like a second look at it. I still haven't figured out highlighting the first item; that would address #282

[wip] Close #254

---

app/actions/index.js
app/components/StatusBar.js
app/components/wrapper.js
app/reducers/status.js
app/screens/Observation/map.js

This notifies the user that they have active surveys.
Example:
This closes #198

active surveys notification

---

app/screens/Observation/view.js

Checks if an observation has an id and changes the labels accordingly.

Closes #280
